apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-secrets-via-file
  name: pod-secrets-via-file
spec:
  containers:
  - image: nginx
    name: pod-secrets-via-file
    resources: {}
    volumeMounts:
    -  name: secret
       mountPath: /secrets
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  -  secret:
       secretName: super-secret
     name: secret 
status: {}
