apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-secrets-via-env
  name: pod-secrets-via-env
spec:
  containers:
  - image: nginx
    name: pod-secrets-via-env
    resources: {}
    envFrom:
    - secretRef:
        name: super-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
