apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: non-persistent-redis
  name: non-persistent-redis
  namespace: pre-pod
spec:
  containers:
  - image: redis
    name: non-persistent-redis
    resources: {}
    volumeMounts:
    - name: cache-control
      mountPath: /data/redis
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: cache-control
    emptyDir: {}
status: {}
