apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-config
spec:
  accessModes: 
  - ReadWriteOnce
  capacity:
     storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/pvsort.txt
