apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: base-pod
  name: base-pod
spec:
  containers:
  - image: busybox
    name: base-pod
    command: ["/bin/sh", "-c", "while true; do echo sri > /dev/null; sleep 3600;done"]
    volumeMounts:
    - name: busybox001
      mountPath: /opt
    resources: {}
  - image: nginx 
    name: base-pod-nginx 
    volumeMounts:
    - name: busybox001
      mountPath: /opt
  initContainers:
  - image: busybox
    name: base-pod1
    command: ["/bin/sh", "-c", "touch /opt/myfile"]
    volumeMounts:
    - name: busybox001
      mountPath: /opt
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: busybox001 
    emptyDir: {}
status: {}
