apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kplabs-selector
  name: kplabs-selector
spec:
  containers:
  - image: nginx
    name: kplabs-selector
    resources: {}
    ports:
    -  containerPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
      disktype: ssd
status: {}
