apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: jenkins
  name: jenkins
  namespace: website-frontend
spec:
  containers:
  - image: jenkins
    name: jenkins
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
